name: Build and Push Wordsmith Images

on:
  push :
   branches :
    - main
  pull_request:
    types: [labeled] # Déclenchement lorsque qu'un label est ajouté à une Pull Request

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: zaidlaasri # Remplacez par votre nom d'utilisateur Docker Hub
      IMAGE_NAME_WEB: wordsmith
      IMAGE_NAME_WORDS: wordsmith
      IMAGE_NAME_DB: wordsmith

    steps:
      # 1. Checkout le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Docker CLI
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Builder les images
      - name: Build Wordsmith Web Image
        run: docker build -t $DOCKER_REGISTRY/$IMAGE_NAME_WEB:webTaga ./web

      - name: Build Wordsmith Words Image
        run: docker build -t $DOCKER_REGISTRY/$IMAGE_NAME_WORDS:wordsTag ./words

      - name: Build Wordsmith DB Image
        run: docker build -t $DOCKER_REGISTRY/$IMAGE_NAME_DB:dbTag ./db

      # 4. Tagger les images avec trois tags
      - name: Tag and Push Images
        run: |
          for IMAGE in $IMAGE_NAME_WEB $IMAGE_NAME_WORDS $IMAGE_NAME_DB; do
            docker tag $DOCKER_REGISTRY/$IMAGE:latest $DOCKER_REGISTRY/$IMAGE:dev
            docker tag $DOCKER_REGISTRY/$IMAGE:latest $DOCKER_REGISTRY/$IMAGE:stable
            docker push $DOCKER_REGISTRY/$IMAGE:latest
            docker push $DOCKER_REGISTRY/$IMAGE:dev
            docker push $DOCKER_REGISTRY/$IMAGE:stable
          done
