name: Build and Push Wordsmith Images

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: zaidlaasri
      IMAGE_NAME_WEB: wordsmith-web
      IMAGE_NAME_WORDS: wordsmith-words
      IMAGE_NAME_DB: wordsmith-db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Images
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME_WEB:latest ./web
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME_WORDS:latest ./words
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME_DB:latest ./db

      - name: Push Images
        run: |
          docker push $DOCKER_REGISTRY/$IMAGE_NAME_WEB:latest
          docker push $DOCKER_REGISTRY/$IMAGE_NAME_WORDS:latest
          docker push $DOCKER_REGISTRY/$IMAGE_NAME_DB:latest

      - name: Cleanup local images
        run: |
          docker rmi $DOCKER_REGISTRY/$IMAGE_NAME_WEB:latest
          docker rmi $DOCKER_REGISTRY/$IMAGE_NAME_WORDS:latest
          docker rmi $DOCKER_REGISTRY/$IMAGE_NAME_DB:latest
